# [START cloudbuild]
steps:
# Clone the repository.
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', '--single-branch', '--branch',
         'master', 'https://github.com/avinabece/mlops_test.git',
         '--depth', '1',
         '--verbose']
  id: 'Clone Repository'


# Deploy the model.
- name: 'gcr.io/dca-sandbox-project-4/cicd:latest'
  entrypoint: 'python'
  args: ['build/test.py']
  dir: 'mlops_test'


# Upload compiled pipeline to GCS.
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'tabular_template.json', 'gs://mlops_poc_health_2022/Avinab_test/']
  dir: 'mlops_test'

