# [START cloudbuild]
steps:
# Clone the repository.
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', '--single-branch', '--branch',
         'master', 'https://github.com/avinabece/mlops_test.git',
         '--depth', '1',
         '--verbose']
  id: 'Clone Repository'

# Install dependencies
- name: 'python:3.9'
  entrypoint: 'pip3'
  args: ["install", "-r", "r.txt", "--user"]

# Deploy the model.
- name: 'python:3.9'
  entrypoint: 'python'
  args: ['test.py']


# Upload compiled pipeline to GCS.
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'tabular_template.json', 'gs://mlops_poc_health_2022/pipeline_json/']
logsBucket: 'gs://mlops_poc_health_2022/logs'
options:
  logging: GCS_ONLY

